In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import json
import os
import psycopg2

In [2]:
#read from the backup file
def read_file(file_name):
    fileDir = os.path.dirname(os.path.realpath('__file__'))
    filename = os.path.join(fileDir, 'backups/'+file_name)
    with open(filename) as my_file:
        db_conf = json.load(my_file)
    return db_conf

In [3]:
#data element table analysis
json_data = read_file('dim_dhis_dataelement')
data_element_dframe = DataFrame(json_data['data']).set_index('index')

data_element_dframe.dtypes
# data_element_dframe

_datecreated          object
_eventexecutionkey    object
_lastaction           object
_mergekey             object
_sourcesystemcode     object
aggregationtype       object
code                  object
dataelementid          int64
dataelementname       object
description           object
domaintype            object
numbertype            object
shortname             object
uid                   object
valuetype             object
zeroissignificant       bool
dtype: object

In [17]:
#data value table analysis
json_data = read_file('fact_dhis_datavalue')
data_value_dframe = DataFrame(json_data['data']).set_index('index')

# data_value_dframe.dtypes
data_value_dframe[['sourceid']]

       sourceid
index
0         44751
1         45114
2         45161
3         51442
4         45161
5         35549
6         45508
7         32821
8         32402
9         39646
10        32551
11        39646
12        35549
13        45201
14        35115
15        45201
16        31858
17        45201
18        39646
19        45201
20        31858
21        45201
22        31858
23        45201
24        35194
25        50011
26        45201
27        32402
28        39646
29        45201
...         ...
70        22699
71        22713
72        22713
73        49679
74        22713
75        22713
76        24044
77       297151
78       297151
79       297151
80        24044
81        24044
82        49745
83        49745
84        24044
85       297153
86        24044
87        49745
88       297153
89        49745
90        24044
91       297153
92       297153
93        49745
94        49745
95       297153
96        49745
97        49733
98        49733
99        49733

[100000 rows x 1 columns]

In [5]:
#dhis period table analysis
json_data = read_file('dim_dhis_period')
period_frame = DataFrame(json_data['data']).set_index('index')

period_frame.dtypes
# data_value_frame[['periodid']]

_datecreated          object
_eventexecutionkey    object
_lastaction           object
_mergekey             object
_sourcesystemcode     object
enddate               object
periodid               int64
periodtypeid           int64
periodtypename        object
startdate             object
yearmonth             object
dtype: object

In [6]:
#dhis period table analysis
json_data = read_file('dim_dhis_indicator')
indicator_frame = DataFrame(json_data['data']).set_index('index')

# indicator_frame.dtypes
indicator_frame[indicator_frame['indicatorid'] == 84107]

,_datecreated,_eventexecutionkey,_lastaction,_mergekey,_sourcesystemcode,annualized,code,denominator,denominatordescription,denominatorsql,...,indicatortypefactor,indicatortypeid,indicatortypename,indicatortypenumber,indicatortypeuid,numerator,numeratordescription,numeratorsql,shortname,uid
index,,,,,,,,,,,,,,,,,,,,,
65,2016-02-01T00:00:00.000Z,None,I,None,None,False,None,#{JOnT3OiMd5o.NhSoXUMPK2K},Estimated live births or preganancy,SELECT value1 as denominator FROM (SELECT CO...,...,100,21017,Percentage,False,gmR4Yqwh6TY,#{JbcvbCEBnu6.NhSoXUMPK2K},WRA Receiving folate,SELECT value1 as numerator FROM (SELECT COAL...,WRA Receiving folate,None

In [ ]:
#categorycombo table analysis
json_data = read_file('dim_dhis_categoryoptioncombo')
categorycombo_dataframe = DataFrame(json_data['data']).set_index('index')

categorycombo_dataframe.dtypes
# data_element_dframe[['dataelementname','description']]

In [ ]:
#categorycombo table analysis
json_data = read_file('dim_dhis_indicatornumerator')
indicator_numerator_dataframe = DataFrame(json_data['data']).set_index('index')

# indicator_numerator_dataframe.dtypes
indicator_numerator_dataframe

In [ ]:
#indicator group table analysis
json_data = read_file('dim_dhis_indicatorgroup')
indicator_group_dataframe = DataFrame(json_data['data']).set_index('index')

indicator_group_dataframe.dtypes
# indicator_group_members_dataframe

In [ ]:
#categorycombo table analysis
json_data = read_file('dim_dhis_indicatorgroupmembers')
indicator_group_members_dataframe = DataFrame(json_data['data']).set_index('index')

indicator_group_members_dataframe.dtypes
# indicator_group_members_dataframe

In [29]:
#categorycombo table analysis
json_data = read_file('dim_dhis_organisationunit')
organisation_unit_dataframe = DataFrame(json_data['data']).set_index('index')

organisation_unit_dataframe.dtypes
# organisation_unit_dataframe[['organisationunitid','mflcode','uid','uuid']]

,organisationunitid,mflcode,uid,uuid
index,,,,
0,512884,NaN,lDSUtXy5gIH,6e651fcf-b8b7-4a05-9b62-fb55a1a138ad
1,513316,NaN,IbIzxMl0Nox,365a68bc-017f-4073-8f3f-5fbe8603f06d
2,423684,NaN,FRVuojduxDT,060dbd69-6c10-419a-a511-1aada53f046e
3,512885,NaN,mUJamp16ulT,f367c361-ff80-48b0-b6a6-bbffd8a3329a
4,7713821,NaN,JeZwi7ZFngx,62ce9b69-5751-4897-8811-67ff93ba1aed
5,6529959,NaN,vbYdPMs0iXI,71cb365c-2326-46d5-979f-9dc94797876d
6,8445672,20550.0,JCWEmzlEsUd,103f40f9-f539-4507-b1cd-8137d7545c28
7,7723507,NaN,SPVRRIHvbIe,6bddde7b-11c6-47a8-bbc8-6b6a333d5693
8,254980,NaN,PIdRPNJNPGu,8e396656-cdc3-48a9-9898-a18f13578557
9,62222,NaN,UOKEv02h8eL,43ea519c-8b2a-4084-b7e2-059efd61275f
10,177765,NaN,IcAY6Oco0YH,8d330184-546d-443e-aa2e-60086ea6bc31
11,3526499,NaN,kXAoZhmJwWB,a1f1ccc3-da4f-45c0-8e6c-3a862b0439f8
12,3513723,NaN,OfhwZ7l8y2f,04d90951-b90b-48ca-bb58-ce53f01839eb
13,423665,NaN,OIHIQljdl2B,ae7b6278-fca3-45ce-ab79-8ddffd53bf9f
14,97907,NaN,c8BwClnyLb8,ff996c43-d891-4164-a0bb-23050cdd6106
15,39443,NaN,Oe4OFL3ogp1,aaf04a56-24cc-4d79-9f34-0126f964baba
16,513704,NaN,WVYx572Ch3P,118bb650-976f-4802-a895-a799945e2d30
17,87024,NaN,bOheTJexEiM,24c332a4-690e-4dcc-839b-05df49e4f82b
18,7723508,NaN,n31IhlwvDXx,b958b77a-b11c-4280-bdfb-611816f1280e
19,3163681,NaN,FbMwYC5g9OA,df97c79f-e234-4e0c-aeff-1a6021b36c0d
20,6535779,NaN,CeC3Dwzhk8m,73894877-8b98-4433-ab5a-f75f0feb1e3e
21,3513724,NaN,X019Xej1Q0H,db2de668-4bec-49e9-aa8d-2f920f9b1543
22,513142,NaN,YqmQnhbNQGw,fc5f3f7e-b861-44fe-9797-26f1f7801277
23,44696,NaN,X5tOKH0s1GU,44eb986b-233e-496e-b9b7-f179f08124d8
24,6535194,NaN,Zm9QO5B0esA,b7f52d2d-cbd7-4a13-b747-835aecbf1b86
25,31670,NaN,lNvNL0l1o4p,51254ffc-9577-45fa-b405-e74d63a32a46
26,6592508,NaN,iBuXrh8ESS2,8c85c6d7-5374-409f-844f-fda7e9e6b459
27,3193931,NaN,g6hccKbypBE,6119361a-2333-4289-a0d0-04a78850752f
28,3163871,NaN,GvNGGOVfj41,a935d815-8fa4-4241-bed7-2d3aeb7719ba
29,3526518,NaN,OUS3GeOf1ou,04e10a22-930e-454a-a694-3f396ac2dba0
...,...,...,...,...
70,257419,18522.0,JMVoyBLwD3X,770f2c0c-b002-4cf4-8eb6-d0e9e884a851
71,433256,602914.0,nGQv7spDUiW,05c06631-f483-4a1e-a8b9-9ac66784ce29
72,433258,602915.0,u9BgGFMlxCv,dce51091-1440-449a-916e-1a885b182b17
73,35641,14596.0,cuGN8a61oOn,96a32c21-4994-41f1-a2ae-7b8fd7cbb6a9
74,34888,10381.0,HxsxJk2Sj0y,e3622ba4-dbd0-4a05-aad0-07f0b2e3be87
75,337398,19644.0,AI32SPyEcuS,adc074d3-2e53-4b0b-b68f-381e3275013f
76,51407,12100.0,iDHeWZFedEx,2ff5a15b-fac9-4f58-b35f-01df99e54b18
77,34947,10708.0,jVhl1A0KGIe,3095ef16-815b-4685-9c19-f7299c553956
78,22713,15654.0,Ohe5HjRN8PF,7f904699-2793-4954-9a68-d56cd4be56b3
79,32090,14067.0,bpyuIqQTies,d67c5bdc-13cc-47d3-b95a-1474478c9ec0
80,34712,10247.0,ptHepSWEFUb,fb1fd209-c292-4143-8704-19a998c70e25
81,38220,15326.0,PxtZobnR8GD,a7d5454a-fdac-4a36-88c3-d0be5ba331e4
82,34799,11119.0,eC9jQw18LEh,c9552ab4-625f-41b2-a0ad-d9a84f119b98
83,45464,11992.0,CCXK8mGTiQq,30921bfe-1f73-4cab-8be9-cda443459264
84,51887,17474.0,wYwV07fk7xt,a0b5e065-e228-446d-a5ef-5ef0b0053f8c
85,34870,10286.0,yfWjbUihHoJ,361c360c-94f2-486c-a221-74c4fb2db5f6
86,49829,12764.0,bQoq24w8gnH,41596e22-eb6d-4b7f-bba2-3d756f83e6c1
87,34723,10361.0,qO76CTmGqak,5dc5ffbb-178e-43c4-bacd-85c5ab7b91fd
88,80214,18051.0,Uma5NXphDL5,ff848cd3-919e-4ce5-9902-eda63da19ba2
89,34756,10669.0,hPCDkK06PhP,8d238824-3916-46e6-ac10-c626ef00865c
90,51420,12443.0,CI9YUNiNvOM,4c73ee48-4d3b-4bf4-8e08-b6290fefbbe3
91,54478,17691.0,lesudC45gPM,1a219572-54e6-4721-b729-e1313ba46188
92,35630,14347.0,sK4BuHXOPqw,4c474490-9b40-4d1c-b2c6-42bcf78ad088
93,45461,12413.0,amP1kWytNm2,2cfa16ed-5fa5-4a06-a019-61fed90e199e
94,34825,10104.0,yVC83EdaWrx,81812a2b-efb9-4414-8917-9cac9a2a6f87
95,49787,12223.0,aqK5rfDMD1h,17eb5658-57a2-413c-96cf-220cec026557
96,87036,10314.0,sxPFMUzGUGB,6b7616dc-19c4-4012-b978-d3486ead6a92
97,38199,15129.0,ZgoaGXYlUAa,c5572dd9-b045-4713-8c54-e84ca03395fe
98,34872,10299.0,vyZ6cmvPtRV,0b7e2e90-a2e6-458b-9a29-b99202292f4c
99,181967,601586.0,qSYTp7oEHUw,dde44327-5d61-4bc0-81ba-edfe8d95f952

In [32]:
organisation_unit_dataframe[organisation_unit_dataframe['organisationunitid'] == 14309]

Empty DataFrame
Columns: [_datecreated, _eventexecutionkey, _lastaction, _mergekey, _sourcesystemcode, address, closeddate, code, contactperson, coordinates, description, email, latitude, longitude, mflcode, openingdate, organisationunitid, organisationunitname, parentid, phonenumber, shortname, uid, uuid]
Index: []

[0 rows x 23 columns]

In [31]:
#get a facility and get data values
#facility table analysis
json_data = read_file('facilities_facility')
facilities_dataframe = DataFrame(json_data['data']).set_index('index')

# facilities_dataframe.dtypes
facilities_dataframe[['code']]

         code
index
0           0
1       14309
2       15744
3       14311
4       15152
5       15715
6       15716
7       15717
8       15155
9       15727
10      15680
11      15756
12      15757
13      14284
14      15759
15      15754
16      14269
17      15751
18      15154
19      14612
20      15724
21      14270
22      15690
23      15698
24      15752
25      15730
26      14308
27      15729
28      15741
29      14522
...       ...
25     100001
26     100010
27     100016
28     100005
29     100030
30     100068
31     100075
32     100020
33     100019
34     100013
35     100072
36     100018
37     100022
38     100021
39     100014
40     100067
41     100074
42     100017
43     100081
44     100071
45     100012
46      12972
47     100082
48     100073
49     100076
50     100066
51      20146
52     100085
53     100083
54     100084

[8855 rows x 1 columns]

In [30]:
facilities_dataframe[['name','id','code']]

,name,id,code
index,,,
0,0,0,0
1,Chelilis Dispensary,28dc6200-882b-4754-b82e-320d2ecc96c7,14309
2,Tuiyobei Dispensary,1b119671-747a-4320-a9d8-d1d15b9e556f,15744
3,Chemaner Dispensary (Bomet),0ec7b67b-6553-457e-842b-7c76271d85df,14311
4,Matanya Dispensary,f735c092-14be-48e4-a8b9-061d8f016c7c,15152
5,Tegego Dispensary,5fb5701b-8cc3-403b-8e91-2881ce45b6e4,15715
6,Tenden Dispensary,fce1ba70-9372-4854-b218-a85a0d698304,15716
7,Tenduet Dispensary,d7bd6fed-b54e-4456-a6fa-9d94cafa4256,15717
8,Matira Dispensary,fe473be4-ed7d-4ec3-b625-3ae5a6736b9a,15155
9,Tinet Dispensary (Koibatek),794d01b4-888b-42f9-a883-9fdb4acad372,15727
10,Sugoi B Dispensary,033a3d92-db8c-4541-9f73-4d772fded8e0,15680
11,Tuturung Dispensary,2a0b3029-0065-4a13-b64c-611f15ca8ee1,15756
12,Tuum Dispensary,7eea3b61-7069-4044-b2ef-2660e16cc6f3,15757
13,Chagaiya Dispensary,11c64ebc-1bb6-4a19-a855-06717b489447,14284
14,Uhuru Dispensary,87c3447d-eab2-41fb-b637-450c9bd1316c,15759
15,Turkwel Dispensary (Loima),64fcde59-83e0-4862-a131-45f4d6854773,15754
16,Borrowonin Dispensary,8a9b88d9-c547-416e-b5f2-73ce02f0bedd,14269
17,Tumoi Dispensary,77c93755-f22f-442a-956f-03b11521ca53,15751
18,Matharu Dispensary,a0b3250f-57cf-41e8-acf7-c3d1b79f3f3e,15154
19,Kabetwa Health Centre,38488512-0075-487f-96d4-492881b8d505,14612
20,Timboiywo Dispensary,2876dc47-1598-4023-aab1-61c272ca0c2c,15724
21,Bossei Dispensary,7bb8b0d6-b942-45a4-bf2f-a2b05e92b163,14270
22,Survey Dispensary,1170070f-11c1-4c7b-bc7a-378e0787a699,15690
23,Tachasis Mission Dispensary,d96f28fe-4336-41a8-9b7d-b8c6df891cb8,15698
24,Tunyo Dispensary,ac0cbdce-4117-45d6-8eee-c1aec5f17cfd,15752
25,Tirriondonin Dispensary,53a73edb-8849-4006-8447-3e737297981c,15730
26,Chelelach Dispensary,f37e1e9d-49f0-42d0-a8f5-e4731d3fc16e,14308
27,Tirimionin Dispensary,bcd0f40e-2a12-45c5-b157-a5b0543e2955,15729
28,Tugen Estate Dispensary,6c0df65f-8fbf-419b-ac15-e56b113adcce,15741
29,GK Prisons Dispensary (Laikipia East),e51a770f-d983-45bc-8891-c83546ba861b,14522
...,...,...,...
25,Test facility Two,b7ce3623-fb76-4fdf-ac5e-414432d823bf,100001
26,Ademba Medical Clinic,754381c8-4a15-4a1c-a20b-f4bd5a81432d,100010
27,Dianes Clinic,96f64a26-8edf-4401-b40d-2b4f0b5c8707,100016
28,Uzima Medical Center - Mathare,e0eb941c-2547-44f3-a5e1-36a5daba150d,100005
29,E_Group Medical,5a2bcd30-501f-470a-a78b-ff31964f4785,100030
30,Rainbow Dispensary (Ruiru),4d4efaad-692c-4c37-8c27-fde2dbf491cb,100068
31,nairobi health centre,4c06ae20-e0c1-485b-8ad8-5e425acac9b0,100075
32,E-KIMBIMBI CLINIC,e08e091f-45b1-409f-a305-b1a2b21afe0a,100020
33,Ndemo health centerNdemo health center Mathare,5a26c88a-9150-4f40-8b54-39ac11889c33,100019
34,E - Testing Facility,e300874f-685f-42a3-8371-cc7137971133,100013
35,Boda Boda Medical Clinic,7d7b38d1-aacc-4e10-b271-e88a0d431550,100072
36,Group E Gladys,4064db4d-98a8-43e9-8910-98753351994a,100018
37,Ngaira District Hospital,366298db-55fa-4ddb-960a-b70ee2805546,100022
38,Group F,47bd3cd8-02de-4070-b59b-257ed15f678e,100021
39,Ruiru,e2ac7efb-8c0c-4d74-9340-0c741054d35e,100014
40,Obama Sub-County Hospital(Nairobi),84e9c061-604f-4b6b-8ffe-62ee8ea1647f,100067
41,Wakulima 123 Hospital,64c06f25-cced-4320-8fb5-99665131d882,100074
42,Group E Sally,39ae7c6b-1e36-4b63-aa68-aa9be59f91e2,100017
43,PONA SANA CLINIC,c6662f44-c906-4fcd-95d0-0af44caa6eae,100081
44,B Health Care,b3f1f598-21db-4afa-9ce3-338e6248c7e7,100071
45,E-Kenol Hospital,d2229b94-61a8-4cdc-b584-6e2ea5e3e48c,100012
46,Huruma (NCCK) Dispensary,4e0dd1d3-0d26-4426-9484-2969cc18dc5a,12972
47,Nyoks Health Center,9cac7443-8e59-4fb4-a70e-8b5e73e6e04c,100082
48,Group Administration Hospital,4736b860-dcc4-4451-b838-5fdcec4bd06b,100073
49,wavinya H.C,cdd5aff0-6e1f-432f-a328-2b3d0caa96c5,100076
50,EDITH NURSING HOME THIKA,9a23c8c3-7de0-400d-b24b-36904513f218,100066
51,KEMRI/CDC Health Services,4a4eabc7-d6d0-401a-94f1-95addc179d32,20146
52,medboardtest1,cb121c79-0ca3-4a97-94f9-1cd8ffa2558f,100085
53,Tiba Healthcare,22036dea-d4dd-4d2a-8f9d-ef492c82143e,100083
54,demofacility,ed6679af-c4f5-4582-97b5-9cc9cd5ec232,100084

In [20]:

data_value_dframe[data_value_dframe['sourceid'] == 44751]

,_datecreated,_eventexecutionkey,_lastaction,_mergekey,_sourcesystemcode,attributeoptioncomboid,categoryoptioncomboid,comment,created,dataelementid,followup,lastupdated,periodid,sourceid,storedby,value
index,,,,,,,,,,,,,,,,
0,2015-12-17T00:00:00.000Z,None,None,None,None,15,510530,None,2014-12-04T15:00:20.414Z,510477,None,2014-12-04T15:00:20.411Z,1185021,44751,Anita,57
50,2015-12-17T00:00:00.000Z,None,None,None,None,15,21316,None,2014-12-04T14:46:53.900Z,21381,None,2014-12-04T14:46:53.899Z,1185021,44751,Anita,40
58,2015-12-17T00:00:00.000Z,None,None,None,None,15,510524,None,2014-12-04T14:52:09.262Z,510482,None,2014-12-04T14:52:09.260Z,1185021,44751,Anita,42
22,2015-12-17T00:00:00.000Z,None,None,None,None,15,510528,None,2014-12-04T14:52:18.041Z,510482,None,2014-12-04T14:52:18.036Z,1185021,44751,Anita,389
87,2015-12-17T00:00:00.000Z,None,None,None,None,15,21316,None,2014-12-04T14:46:37.041Z,21377,None,2014-12-04T14:46:37.038Z,1185021,44751,Anita,3
44,2015-12-17T00:00:00.000Z,None,None,None,None,15,513994,None,2014-12-04T15:05:12.287Z,513973,None,2014-12-04T15:05:12.284Z,1185021,44751,Anita,43
0,2015-12-17T00:00:00.000Z,None,None,None,None,15,510538,None,2014-12-04T14:50:26.795Z,510545,None,2014-12-04T14:50:26.791Z,1185021,44751,Anita,17
41,2015-12-17T00:00:00.000Z,None,None,None,None,15,513997,None,2014-12-04T15:07:13.815Z,513960,None,2014-12-04T15:07:13.812Z,1185021,44751,Anita,100
63,2015-12-17T00:00:00.000Z,None,None,None,None,15,21315,None,2014-12-04T14:46:51.289Z,21381,None,2014-12-04T14:46:51.285Z,1185021,44751,Anita,63
65,2015-12-17T00:00:00.000Z,None,None,None,None,15,21260,None,2014-12-04T14:47:34.433Z,21396,None,2014-12-04T14:47:34.429Z,1185021,44751,Anita,5
68,2015-12-17T00:00:00.000Z,None,None,None,None,15,510538,None,2014-12-04T14:50:55.953Z,510547,None,2014-12-04T14:50:55.949Z,1185021,44751,Anita,17
91,2015-12-17T00:00:00.000Z,None,None,None,None,15,510523,None,2014-12-04T14:55:03.550Z,510470,None,2014-12-04T14:55:03.547Z,1185021,44751,Anita,20
96,2015-12-17T00:00:00.000Z,None,None,None,None,15,510530,None,2014-12-04T14:55:09.436Z,510470,None,2014-12-04T14:55:09.433Z,1185021,44751,Anita,20
43,2015-12-17T00:00:00.000Z,None,None,None,None,15,21261,None,2014-12-04T14:46:06.619Z,21367,None,2014-12-04T14:46:06.615Z,1185021,44751,Anita,6
52,2015-12-17T00:00:00.000Z,None,None,None,None,15,21316,None,2014-12-04T14:46:48.250Z,21379,None,2014-12-04T14:46:48.249Z,1185021,44751,Anita,89
17,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T14:49:40.577Z,510540,None,2014-12-04T14:49:40.575Z,1185021,44751,Anita,15
41,2015-12-17T00:00:00.000Z,None,None,None,None,15,510523,None,2014-12-04T15:01:09.565Z,510479,None,2014-12-04T15:01:09.563Z,1185021,44751,Anita,20
21,2015-12-17T00:00:00.000Z,None,None,None,None,15,510530,None,2014-12-04T14:52:02.516Z,510482,None,2014-12-04T14:52:02.513Z,1185021,44751,Anita,42
60,2015-12-17T00:00:00.000Z,None,None,None,None,15,510523,None,2014-12-04T15:00:07.380Z,510477,None,2014-12-04T15:00:07.377Z,1185021,44751,Anita,52
51,2015-12-17T00:00:00.000Z,None,None,None,None,15,513996,None,2014-12-04T15:09:04.486Z,514007,None,2014-12-04T15:09:04.483Z,1185021,44751,Anita,1758
72,2015-12-17T00:00:00.000Z,None,None,None,None,15,510537,None,2014-12-04T14:51:13.888Z,510549,None,2014-12-04T14:51:13.886Z,1185021,44751,Anita,76
73,2015-12-17T00:00:00.000Z,None,None,None,None,15,510538,None,2014-12-04T14:51:18.710Z,510549,None,2014-12-04T14:51:18.705Z,1185021,44751,Anita,7
1,2015-12-17T00:00:00.000Z,None,None,None,None,15,510531,None,2014-12-04T15:00:33.240Z,510477,None,2014-12-04T15:00:33.238Z,1185021,44751,Anita,100
13,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:03:08.824Z,3224514,None,2014-12-04T15:03:08.823Z,1185021,44751,Anita,9
15,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:03:09.712Z,3224516,None,2014-12-04T15:03:09.710Z,1185021,44751,Anita,9
22,2015-12-17T00:00:00.000Z,None,None,None,None,15,514000,None,2014-12-04T15:06:13.797Z,513975,None,2014-12-04T15:06:13.794Z,1185021,44751,Anita,15
99,2015-12-17T00:00:00.000Z,None,None,None,None,15,513996,None,2014-12-04T15:07:40.894Z,514001,None,2014-12-04T15:07:40.891Z,1185021,44751,Anita,5
5,2015-12-17T00:00:00.000Z,None,None,None,None,15,513996,None,2014-12-04T15:08:19.811Z,514004,None,2014-12-04T15:08:19.808Z,1185021,44751,Anita,2
16,2015-12-17T00:00:00.000Z,None,None,None,None,15,20673,None,2014-12-04T15:17:24.781Z,20952,None,2014-12-04T15:18:08.479Z,1185021,44751,Anita,34
41,2015-12-17T00:00:00.000Z,None,None,None,None,15,21260,None,2014-12-04T14:47:48.801Z,21397,None,2014-12-04T14:47:48.798Z,1185021,44751,Anita,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,2015-12-17T00:00:00.000Z,None,None,None,None,15,21316,None,2014-12-04T15:14:33.101Z,164950,None,2014-12-04T15:14:33.097Z,1185021,44751,Anita,50
74,2015-12-17T00:00:00.000Z,None,None,None,None,15,513994,None,2014-12-04T15:10:57.200Z,514009,None,2014-12-04T15:10:57.197Z,1185021,44751,Anita,1
87,2015-12-17T00:00:00.000Z,None,None,None,None,15,21316,None,2014-12-04T15:15:14.972Z,62012,None,2014-12-04T15:15:14.969Z,1185021,44751,Anita,40
31,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:37:53.604Z,21487,None,2014-12-04T15:37:53.600Z,1185021,44751,Anita,44
74,2015-12-17T00:00:00.000Z,None,None,None,None,15,20673,None,2014-12-04T15:19:29.213Z,21449,None,2014-12-04T15:19:29.210Z,1185021,44751,Anita,24
40,2015-12-17T00:00:00.000Z,None,None,None,None,15,21316,None,2014-12-04T15:13:06.567Z,77842,None,2014-12-04T15:13:06.563Z,1185021,44751,Anita,61
39,2015-12-17T00:00:00.000Z,None,None,None,None,15,21315,None,2014-12-04T15:13:51.702Z,164978,None,2014-12-04T15:13:51.699Z,1185021,44751,Anita,36
54,2015-12-17T00:00:00.000Z,None,None,None,None,15,21316,None,2014-12-04T15:14:03.154Z,164978,None,2014-12-04T15:14:03.150Z,1185021,44751,Anita,43
11,2015-12-17T00:00:00.000Z,None,None,None,None,15,21315,None,2014-12-04T15:14:44.014Z,164952,None,2014-12-04T15:14:44.011Z,1185021,44751,Anita,36
17,2015-12-17T00:00:00.000Z,None,None,None,None,15,21316,None,2014-12-04T15:15:24.856Z,77848,None,2014-12-04T15:15:24.854Z,1185021,44751,Anita,148
37,2015-12-17T00:00:00.000Z,None,None,None,None,15,23581,None,2014-12-04T15:27:46.034Z,20967,None,2014-12-04T15:27:46.030Z,1185021,44751,Anita,6
61,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:33:29.764Z,21475,None,2014-12-04T15:33:29.761Z,1185021,44751,Anita,40
5,2015-12-17T00:00:00.000Z,None,None,None,None,15,21316,None,2014-12-04T15:15:06.054Z,165761,None,2014-12-04T15:15:06.051Z,1185021,44751,Anita,74
4,2015-12-17T00:00:00.000Z,None,None,None,None,15,23580,None,2014-12-04T15:27:21.643Z,20967,None,2014-12-04T15:27:21.639Z,1185021,44751,Anita,22
7,2015-12-17T00:00:00.000Z,None,None,None,None,15,23583,None,2014-12-04T15:27:52.815Z,20967,None,2014-12-04T15:27:52.813Z,1185021,44751,Anita,5
85,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:26:22.635Z,842706,None,2014-12-04T15:26:22.633Z,1185021,44751,Anita,22
25,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:25:15.470Z,842704,None,2014-12-04T15:25:15.466Z,1185021,44751,Anita,2
30,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:29:31.462Z,23568,None,2014-12-04T15:29:31.460Z,1185021,44751,Anita,2
45,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:38:48.421Z,21490,None,2014-12-04T15:38:48.396Z,1185021,44751,Anita,134
46,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T14:08:33.058Z,288509,None,2014-12-04T15:39:05.925Z,1185021,44751,Anita,2014-12-03
8,2015-12-17T00:00:00.000Z,None,None,None,None,15,20673,None,2014-12-04T15:24:31.215Z,20944,None,2014-12-04T15:24:31.212Z,1185021,44751,Anita,31
94,2015-12-17T00:00:00.000Z,None,None,None,None,15,20673,None,2014-12-04T15:24:09.276Z,792266,None,2014-12-04T15:24:09.273Z,1185021,44751,Anita,10
29,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:32:06.320Z,21467,None,2014-12-04T15:32:06.316Z,1185021,44751,Anita,140
33,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:38:06.860Z,21489,None,2014-12-04T15:38:06.856Z,1185021,44751,Anita,30
9,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:39:02.603Z,21492,None,2014-12-04T15:39:02.599Z,1185021,44751,Anita,34
20,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:29:10.023Z,23567,None,2014-12-04T15:29:10.021Z,1185021,44751,Anita,10
49,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:31:33.795Z,21464,None,2014-12-04T15:31:33.793Z,1185021,44751,Anita,160
72,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:38:53.918Z,21491,None,2014-12-04T15:38:53.915Z,1185021,44751,Anita,183
95,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:33:07.762Z,3079146,None,2014-12-04T15:33:07.759Z,1185021,44751,Anita,29
62,2015-12-17T00:00:00.000Z,None,None,None,None,15,15,None,2014-12-04T15:33:52.989Z,21476,None,2014-12-04T15:33:52.986Z,1185021,44751,Anita,150

In [ ]:
data_element_dframe[['dataelementid','dataelementname']]

In [ ]:
data_element_dframe[data_element_dframe['dataelementid']==510477]['dataelementname']

In [11]:
#data value table analysis
json_data = read_file('fact_dhis_datavalue')
data_value_dframe = DataFrame(json_data['data']).set_index('index')

data_value_dframe.dtypes
# data_value_dframe[['periodid']]

_datecreated              object
_eventexecutionkey        object
_lastaction               object
_mergekey                 object
_sourcesystemcode         object
attributeoptioncomboid     int64
categoryoptioncomboid      int64
comment                   object
created                   object
dataelementid              int64
followup                  object
lastupdated               object
periodid                   int64
sourceid                   int64
storedby                  object
value                     object
dtype: object

In [ ]:
data_value_dframe[['periodid','value','sourceid']]

In [ ]:
data_value_dframe[:1][['dataelementid','value']]

In [ ]:
#dhis period table analysis
json_data = read_file('dim_dhis_period')
period_frame = DataFrame(json_data['data']).set_index('index')

period_frame.dtypes
# data_value_frame[['periodid']]

In [ ]:
period_frame[['yearmonth','periodtypeid']]

In [ ]:
period_frame[period_frame['periodid']==1185021]

In [ ]:
#dhis period table analysis
json_data = read_file('dim_dhis_indicator')
indicator_frame = DataFrame(json_data['data']).set_index('index')

indicator_frame.dtypes
# indicator_frame[['']]

In [ ]:
indicator_frame[['denominator','indicatorname']]

In [ ]:
merged = pd.merge(data_value_dframe,data_element_dframe, on='dataelementid', how='inner')

In [ ]:
merged

In [ ]:
merged[['dataelementid','value', 'dataelementname','periodid','sourceid']]

In [ ]:
#indicator table analysis
json_data = read_file('dim_dhis_indicator')
indicator_dataframe = DataFrame(json_data['data']).set_index('index')

indicator_dataframe.dtypes
# data_element_dframe[['dataelementname','description']]

In [ ]:
#categorycombo table analysis
json_data = read_file('dim_dhis_categoryoptioncombo')
categorycombo_dataframe = DataFrame(json_data['data']).set_index('index')

categorycombo_dataframe.dtypes
# data_element_dframe[['dataelementname','description']]

In [ ]:
#categorycombo table analysis
json_data = read_file('dim_dhis_indicatordenominator')
indicator_denomenator_dataframe = DataFrame(json_data['data']).set_index('index')

indicator_denomenator_dataframe.dtypes
# data_element_dframe[['dataelementname','description']]

In [ ]:
#categorycombo table analysis
json_data = read_file('dim_dhis_indicatornumerator')
indicator_numerator_dataframe = DataFrame(json_data['data']).set_index('index')

indicator_numerator_dataframe.dtypes
# data_element_dframe[['dataelementname','description']]

In [ ]:

#categorycombo table analysis
json_data = read_file('dim_dhis_indicatorgroupmembers')
indicator_group_members_dataframe = DataFrame(json_data['data']).set_index('index')

indicator_group_members_dataframe.dtypes
# data_element_dframe[['dataelementname','description']]

In [ ]:
indicator_group_members_dataframe

In [ ]:
#categorycombo table analysis
json_data = read_file('dim_dhis_organisationunit')
organisation_unit_dataframe = DataFrame(json_data['data']).set_index('index')

organisation_unit_dataframe.dtypes
# data_element_dframe[['dataelementname','description']]

In [ ]:
organisation_unit_dataframe[['organisationunitname','mflcode']]

In [ ]:
#datavalues in dataelements 
json_data = read_file('dim_dhis_dataelement')
dataelement_dframe = DataFrame(json_data['data']).set_index('index')
dataelement_dframe = dataelement_dframe[dataelement_dframe['dataelementid']==510477]
# dataelement_dframe.dtypes
# dataelement_dframe

json_data = read_file('fact_dhis_datavalue')
datavalue_dframe = DataFrame(json_data['data']).set_index('index')


# datavalue_dframe
pd.merge(datavalue_dframe, dataelement_dframe, on='dataelementid')